require(tidyverse)
require(readxl)
ss=read_xlsx("Proj_12574____STATS.xlsx")
ss
ss %>% ggplot(aes(Sample,Total))
ss %>% ggplot(aes(Sample,Total)) + theme_light()
ss %>% ggplot(aes(Sample,Total)) + theme_light() + theme(axis.text.x = element_text(vjust = grid::unit(c(-2, 0, 2), "points")))
ss %>% ggplot(aes(Sample,Total)) + theme_light() + theme(axis.text.x = element_text(vjust = grid::unit(c(0, 2), "points")))
ss %>% ggplot(aes(Sample,Total)) + theme_light() + theme(axis.text.x = element_text(vjust = grid::unit(c(-2, 2), "points")))
ss %>% ggplot(aes(Sample,Total)) + theme_light() + theme(axis.text.x = element_text(vjust = grid::unit(c(-2, 0, 2), "points")))
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip()
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip() + geom_bar()
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip() + geom_bar(stat="identity")
ss %>% ggplot(aes(Sample,Total/1e6)) + theme_light() + coord_flip() + geom_bar(stat="identity")
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip() + geom_bar(stat="identity")
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))
ss %>% ggplot(aes(Sample,Total)) + theme_light() + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6))
ss %>% ggplot(aes(Sample,Total)) + theme_light(base_size=12) + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6))
ss %>% ggplot(aes(Sample,Total)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6))
ss %>% ggplot(aes(Sample,Total)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + ggtitle("Total Reads")
pg1=ss %>% ggplot(aes(Sample,Total)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="identity") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + ggtitle("Total Reads")
ss
ss %>% gather(Metric,Value,-Sample)
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library"))
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric))
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric))+theme_light(base_size=16)+geom_bar(stat="Identity")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric))+theme_light(base_size=16)+geom_bar(stat="Identity",position="dodge")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6))
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_brewer(palette="Set3")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_brewer(palette="Dark2")
library("ggsci")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_npg()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="black") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_npg()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey90") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_npg()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_npg()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_aaas()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_nejm()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_lancet()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_jama()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_jco()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_ucscgb()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_d3()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_locuszoom()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago()
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago("dark")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago("light")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago("light")
pg2=ss %>% gather(Metric,Value,-Sample) %>% filter(Metric %in% c("Total","Num.Processed","Num.Library")) %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") + scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6)) + scale_fill_uchicago("light")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric=="PCT.Useable")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric=="PCT.Useable") %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric=="PCT.Useable") %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") +  scale_fill_uchicago("light")
ss %>% gather(Metric,Value,-Sample) %>% filter(Metric=="PCT.Useable") %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") +  scale_fill_uchicago("light") + scale_y_continuous(labels = scales::percent_format(accuracy = 1))
pg3=ss %>% gather(Metric,Value,-Sample) %>% filter(Metric=="PCT.Useable") %>% ggplot(aes(Sample,Value,fill=Metric)) + theme_light(base_size=16) + coord_flip() + geom_bar(stat="Identity",position="dodge",color="grey20") +  scale_fill_uchicago("light") + scale_y_continuous(labels = scales::percent_format(accuracy = 1))
pdf(file="Proj_12574____STATS.pdf",width=11,height=8.5)
print(pg1);print(pg2);print(pg3)
dev.off()
pdf(file="Proj_12574____STATS.pdf",width=11,height=8.5)
print(pg2);print(pg3)
dev.off()
