#!/usr/bin/env python3

import sys
from tools.FASTQ import read_FASTQ

import argparse

argParser=argparse.ArgumentParser()
argParser.add_argument('fastq',type=str)
args=argParser.parse_args()

for rr in read_FASTQ(args.fastq):
    print(rr.desc,rr.seq[:25],rr.qual[:25])

