#!/usr/bin/env python3

import sys
from tools.FASTQ import read_FASTQ

import argparse

argParser=argparse.ArgumentParser()
argParser.add_argument('seqFile',type=str,help="File of target sequences")
argParser.add_argument('fastq',type=str,help="FASTQ file")
args=argParser.parse_args()

args.seqFile

print(args)

seqs=[s.strip() for s in open(args.seqFile,"r").readlines()]
MAX_COUNT=100
count=0

for rr in read_FASTQ(args.fastq):
    if count >= MAX_COUNT:
        break
        
    for si in seqs:
        if count >= MAX_COUNT:
            break
            
        pos=rr.seq.find(si)
        if pos>-1:
            print("#SCAN#",si, pos,
                "5':", rr.seq[(pos-20):pos],
                "3':", rr.seq[(pos+len(si)):(pos+len(si)+20)]
                )
            sys.stdout.flush()
            count=count+1


