#!/usr/bin/env python3

import sys
from tools.FASTQ import read_FASTQ

import argparse

argParser=argparse.ArgumentParser()
argParser.add_argument('seqFile',type=str,help="File of target sequences")
argParser.add_argument('fastq',type=str,help="FASTQ file")
args=argParser.parse_args()

args.seqFile

print(args)

seqs=[s.strip() for s in open(args.seqFile,"r").readlines()]

for rr in read_FASTQ(args.fastq):
    for si in seqs:
        pos=rr.seq.find(si)
        if pos>-1:
            print("#SCAN#",si, rr.seq.find(si), rr.seq[(pos-20):pos],rr.seq[(pos+len(si)):(pos+len(si)+20)],rr.seq[(pos+len(si)):-1])
            sys.stdout.flush()


#     print(rr.desc,rr.seq[:25],rr.qual[:25])

